# Generated by Django 5.0.6 on 2024-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_shared_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_posts',
            name='content',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='written_posts',
            name='content',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
