# Generated by Django 5.0.6 on 2024-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_shared_posts_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='written_posts',
            name='content',
            field=models.TextField(max_length=1500),
        ),
    ]
