# Generated by Django 5.0.6 on 2024-06-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_written_posts_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='written_posts',
            name='content',
        ),
    ]
