# Generated by Django 5.0.6 on 2024-06-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_written_posts_content_alter_shared_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_posts',
            name='shared_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Posts.written_posts'),
            preserve_default=False,
        ),
    ]
