# Generated by Django 5.0.6 on 2024-06-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_shared_posts_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='shared_posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Posts.shared_posts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='written_posts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Posts.written_posts'),
            preserve_default=False,
        ),
    ]
