# Generated by Django 5.0.6 on 2024-06-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_posts_shared_posts_posts_written_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
