# Generated by Django 5.0.6 on 2024-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_posts',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='written_posts',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
