# Generated by Django 5.0.6 on 2024-06-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_shared_posts_comments_shared_posts_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_posts',
            name='shares',
        ),
    ]
