# Generated by Django 5.0.6 on 2024-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_follow_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_request',
            name='accept',
        ),
        migrations.AddField(
            model_name='follow_request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
