# Generated by Django 5.0.6 on 2024-06-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_user_profile_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='followings_count',
        ),
    ]
