# Generated by Django 5.0.6 on 2024-06-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_user_profile_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow_request',
            old_name='requested',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follow_request',
            old_name='requester',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follow_request',
            unique_together={('follower', 'followed')},
        ),
    ]
