# Generated by Django 5.0.6 on 2024-06-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_rename_requested_follow_request_followed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow_request',
            old_name='followed',
            new_name='requested',
        ),
        migrations.RenameField(
            model_name='follow_request',
            old_name='follower',
            new_name='requester',
        ),
        migrations.AlterUniqueTogether(
            name='follow_request',
            unique_together={('requester', 'requested')},
        ),
    ]
