# Generated by Django 5.0.6 on 2024-06-30 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_rename_commet_comment_writtenposts_comment'),
        ('Posts', '0016_remove_video_post_written_posts_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Notification_on_SharedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whohasbeencommentedhared', to=settings.AUTH_USER_MODEL)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whocommentsshared', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.shared_posts')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Notification_on_WrittenPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whohasbeencommented', to=settings.AUTH_USER_MODEL)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whocomments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.written_posts')),
            ],
        ),
    ]
