# Generated by Django 5.0.6 on 2024-06-28 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0003_like_notification_on_sharedposts'),
        ('Posts', '0016_remove_video_post_written_posts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_notification_on_sharedposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.shared_posts'),
        ),
    ]
